### ISSUE TITLE
Page: Add text

### ISSUE THREAD

**Issue by FlorianCassayre** [com-480-data-visualization/data-visualization-project-2021-ufa#9]
Add minimal titles describing what each visualization represents. This is also a good occasion to annotate the axis. Beware not to break the layout!

**Bonus**: create information bubbles that display a longer message on mouse hover.

**Comment by FlorianCassayre** [comment]
Please add the infobubbles for the remaining plots (bar, time & keywords).

**Comment by adina-ciubotaru** [comment]
On it
